# Generated by Django 3.2.4 on 2021-06-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='created_at',
            new_name='posted_at',
        ),
    ]
