# Generated by Django 3.2.4 on 2021-06-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_tweet_posted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='name',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
